### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by Faraz1243**

### CODE REVIEW

**Comment by UsmanUet276** [comment]
You have to add stat sections after testimonials

**Comment by UsmanUet276** [comment]
# Not appproved

**Comment by Faraz1243** [comment]
I'll change the file again.

**Comment by UsmanUet276** [comment]
Pls change it

**Review by UsmanUet276 — COMMENTED** [review]
# Over All Approving
This Contribution is looking Good! So I am approving it

**Pull request merged**
